import { Food } from "./app/shared/models/food";
import { Tag } from "./app/shared/models/tags";

export const sample_foods: Food[]=[
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: "10 to 20 min",
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageURl: ['assets/200.jpg'],
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: "10 to 15 min",
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageURl: ['assets/201.jpg'],
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: "10 to 20 min",
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageURl:[ 'assets/202.jpg'],
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: "10 to 15 min",
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageURl: ['assets/203.jpg'],
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: "10 to 15 min",
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageURl:[ 'assets/204.jpg'],
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: "15 to 20 min",
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageURl: ['assets/205.webp'],
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]
export const sample_tags:Tag[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]
